joint_names:
  - $(arg right_prefix)joint_1
  - $(arg right_prefix)joint_2
  - $(arg right_prefix)joint_3
  - $(arg right_prefix)joint_4
  - $(arg right_prefix)joint_5
  - $(arg right_prefix)joint_6
  - $(arg right_prefix)joint_7
maximum_velocities:
  - 0.8727
  - 0.8727
  - 0.8727
  - 0.8727
  - 0.8727
  - 0.8727
  - 0.8727
maximum_accelerations:
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  - 10.0
  - 10.0
  - 10.0
